'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class fct_gmi700_pbsEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=fct_gmi700_pbsEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property PLC_MASTER() As DbSet(Of PLC_MASTER)
    Public Overridable Property PLC_MEMORY_MAP() As DbSet(Of PLC_MEMORY_MAP)
    Public Overridable Property PROCESSes() As DbSet(Of PROCESS)
    Public Overridable Property RESULTs() As DbSet(Of RESULT)
    Public Overridable Property V_RESULT_HISTORY() As DbSet(Of V_RESULT_HISTORY)
    Public Overridable Property PART_NO_MAPPING() As DbSet(Of PART_NO_MAPPING)

End Class
