'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PROCESS
    Public Property PROCESS_ID As Integer
    Public Property PROCESS_NAME As String
    Public Property PROCESS_SEQ As Integer

    Public Overridable Property PLC_MASTER As ICollection(Of PLC_MASTER) = New HashSet(Of PLC_MASTER)
    Public Overridable Property RESULTs As ICollection(Of RESULT) = New HashSet(Of RESULT)

End Class
