'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLC_MASTER
    Public Property PLC_ID As Integer
    Public Property PLC_DESCR As String
    Public Property PROCESS_ID As Integer
    Public Property PLC_NET As Integer
    Public Property PLC_NODE As Integer
    Public Property PLC_UNIT As Integer
    Public Property PC_WRITE_ADDRESS As Integer
    Public Property PLC_WRITE_ADDRESS As Integer
    Public Property INCOMING_FLAG As Byte

    Public Overridable Property PROCESS As PROCESS

End Class
